version: "3.2"
services:

    # app
    webpulse:
        build:
            context: ./docker/app
            dockerfile: ./Dockerfile
        # restart: always
        ports:
            - ${DOCKER_PORT}:80
        volumes:
            - .:/var/www/html/
            - ../admin:/var/www/admin
        env_file:
            - .env

    # phpMyAdmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mariadb

    # MariaDB service
    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
