version: "3.2"
services:
    webpulse:
        build:
            context: ./docker/app
            dockerfile: ./Dockerfile
        ports:
            - "${DOCKER_PORT}:80"
        volumes:
            - .:/var/www/html/
            - ../admin:/var/www/admin
        env_file:
            - .env
        depends_on:
            - phpmyadmin
            - mariadb
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
